@startuml packages_atlast_sc.calculator
set namespaceSeparator none
package "atlast_sc" as atlast_sc {
}
package "atlast_sc.atmosphere_params" as atlast_sc.atmosphere_params {
}
package "atlast_sc.calculator" as atlast_sc.calculator {
}
package "atlast_sc.config" as atlast_sc.config {
}
package "atlast_sc.data" as atlast_sc.data {
}
package "atlast_sc.efficiencies" as atlast_sc.efficiencies {
}
package "atlast_sc.exceptions" as atlast_sc.exceptions {
}
package "atlast_sc.models" as atlast_sc.models {
}
package "atlast_sc.temperatures" as atlast_sc.temperatures {
}
package "atlast_sc.utils" as atlast_sc.utils {
}
atlast_sc.calculator --> atlast_sc.atmosphere_params
atlast_sc.calculator --> atlast_sc.config
atlast_sc.calculator --> atlast_sc.efficiencies
atlast_sc.calculator --> atlast_sc.exceptions
atlast_sc.calculator --> atlast_sc.models
atlast_sc.calculator --> atlast_sc.temperatures
atlast_sc.calculator --> atlast_sc.utils
atlast_sc.config --> atlast_sc.models
atlast_sc.data --> atlast_sc.utils
atlast_sc.models --> atlast_sc.data
atlast_sc.models --> atlast_sc.exceptions
@enduml
